# Generated by Django 5.0.1 on 2024-01-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='price_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
